---
# ==============================================================================
# УСТАНОВКА И НАСТРОЙКА PROMETHEUS (только на prometheus-host)
# ==============================================================================

- name: Ensure Prometheus config directory exists
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
  when: inventory_hostname == 'prometheus-host'

- name: Deploy clean Prometheus configuration file
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: "{{ groups['web'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '$', ':9100') | list }}"
       - job_name: 'nginx_exporter'
          static_configs:
            - targets: "{{ groups['web'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '$', ':9113') | list }}"
  when: inventory_hostname == 'prometheus-host'

# ==============================================================================
# УСТАНОВКА И НАСТРОЙКА GRAFANA (только на grafana-host)
# ==============================================================================

- name: Download Grafana Enterprise package from verified mirror path
  shell: "wget -q -O /tmp/grafana-enterprise_12.4.5_27960329288_linux_amd64.deb https://mirror.yandex.ru/mirrors/packages.grafana.com/oss/deb/pool/main/g/grafana-enterprise/grafana-enterprise_12.4.5_27960329288_linux_amd64.deb"
  when: inventory_hostname == 'grafana-host'

- name: Install Grafana deb package locally
  shell: "dpkg -i /tmp/grafana-enterprise_12.4.5_27960329288_linux_amd64.deb || true"
  when: inventory_hostname == 'grafana-host'

- name: Fix missing dependencies and force start grafana
  shell: |
    apt-get install -f -y
    systemctl daemon-reload
    systemctl enable grafana-server
    systemctl start grafana-server
  when: inventory_hostname == 'grafana-host'
