---
- name: Update apt cache and install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy static website content
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Install Node Exporter via apt
  apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Node Exporter is running and enabled
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install Nginx Prometheus Exporter via apt
  apt:
    name: prometheus-nginx-exporter
    state: present

- name: Configure Nginx stub_status for exporter
  copy:
    dest: /etc/nginx/conf.d/status.conf
    content: |
      server {
          listen 127.0.0.1:80;
          server_name localhost;
          location /metrics {
              stub_status on;
              access_log off;
              allow 127.0.0.1;
              deny all;
          }
      }
  notify: Restart nginx

- name: Ensure Nginx Prometheus Exporter is running and enabled
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
