[bastion]
bastion-host ansible_host=84.252.131.124 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[web]
web-server-1 ansible_host=10.120.10.11 ansible_user=ubuntu
web-server-2 ansible_host=10.130.10.22 ansible_user=ubuntu

[monitoring]
prometheus-host ansible_host=10.120.10.30 ansible_user=ubuntu
grafana-host ansible_host=51.250.70.184 ansible_user=ubuntu

[logs]
elasticsearch-host ansible_host=10.120.10.18 ansible_user=ubuntu
kibana-host ansible_host=93.77.183.244 ansible_user=ubuntu
