[bastion]
bastion-host ansible_host=158.160.40.239 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[web]
web-server-1 ansible_host=10.120.10.10 ansible_user=ubuntu
web-server-2 ansible_host=10.130.10.26 ansible_user=ubuntu

[monitoring]
prometheus-host ansible_host=10.120.10.14 ansible_user=ubuntu
grafana-host ansible_host=10.110.10.11 ansible_user=ubuntu

[logs]
elasticsearch-host ansible_host=10.120.10.25 ansible_user=ubuntu
kibana-host ansible_host=10.110.10.18 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q ubuntu@158.160.40.239 -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"'
